version: '3'

services:

  web:
    restart: "on-failure"
    container_name: punzh_django
    volumes:
      - ./app:/app
    build:
      context: ./
      dockerfile: images/django/Dockerfile
    depends_on:
      - db
    command: python manage.py runserver --insecure 0.0.0.0:8000
    ports:
      - 80:8000
    networks:
        - punzh-net

  db:
    container_name: punzh_db
    image: postgres
    restart: "on-failure"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=punzh_dict
    networks:
        - punzh-net

  pgadmin:
    container_name: punzh_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=fedoto4kin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD:-12345}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    depends_on:
      - "db"
    networks:
        - punzh-net

networks:
  punzh-net:
    driver: bridge